### ISSUE TITLE
AWS S3 Sink Connector throwing "S3Exception: The provided token has expired

### ISSUE THREAD

**Issue by warmuuh** [lensesio/stream-reactor#1650]
It seems that lenses (or the used AWS SDK Setup) is caching the initial token and not refreshing it.

### What version of the Stream Reactor are you reporting this issue for?
kafka-connect-aws-s3-8.1.28.zip

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?
kafka version 3.8.1

### Do you have a supported version of the data source/sink .i.e Cassandra 3.0.9?
source/sink = s3

### Have you read the [docs](https://docs.lenses.io/connectors/)?
yes

### What is the expected behaviour?

after an hour (current session token expired and got renewed), the new token should be used

### What was observed?
the old token is used and exception is thrown:
```
software.amazon.awssdk.services.s3.model.S3Exception: The provided token has expired. (Service: S3, Status Code: 400, Request ID:...)
...
        at software.amazon.awssdk.services.s3.DefaultS3Client.listObjectsV2(DefaultS3Client.java:7704)
...
        at io.lenses.streamreactor.connect.aws.s3.storage.AwsS3StorageInterface.$anonfun$listRecursive$1(AwsS3StorageInterface.scala:129)
```

### What is your Connect cluster configuration (connect-avro-distributed.properties)?
using strimzi, so slightly different format:

```yaml
    config:
      group.id: connect-test-connect
      ....
      key.converter: org.apache.kafka.connect.converters.ByteArrayConverter
      value.converter: org.apache.kafka.connect.converters.ByteArrayConverter
```

### What is your connector properties configuration (my-connector.properties)?

```yaml
  class: io.lenses.streamreactor.connect.aws.s3.sink.S3SinkConnector
  tasksMax: 1
  config:
    topics: test-topic-backup
    # 10 second flush.interval for testing
    connect.s3.kcql: >-
      INSERT INTO backup-bucket
      SELECT * FROM test-topic-backup 
      STOREAS `JSON` 
      PROPERTIES ('store.envelope'=true, 'flush.interval'=10)
    key.converter: org.apache.kafka.connect.converters.ByteArrayConverter
    value.converter: org.apache.kafka.connect.converters.ByteArrayConverter
    connect.s3.aws.auth.mode: Default
    connect.s3.aws.region: eu-central-1
```

AWS token is setup like this:
```
AWS_SHARED_CREDENTIALS_FILE=/etc/iam-secret/credentials
AWS_CREDENTIAL_PROFILES_FILE=/etc/iam-secret/credentials
```
this file gets refreshed every hour. usually (for our other java applications), the aws sdk picks up the changed token. here, i can see that lenses is still using the old tokens (by debug-logging of `org.apache.http.wire`)
