### ISSUE TITLE
Please allow custom endpoints for your Amazon Web Services S3 Sink Connector

### ISSUE THREAD

**Issue by seanjhulse** [lensesio/stream-reactor#741]
# Issue Guidelines

Please review these questions before submitting any issue?

### What version of the Stream Reactor are you reporting this issue for?

**2.0.0-2.4.0**

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?

Yes.

### Do you have a supported version of the data source/sink .i.e Cassandra 3.0.9?

Yes. https://github.com/lensesio/stream-reactor/tree/master/kafka-connect-aws-s3

### Have you read the [docs](https://docs.lenses.io/connectors/)?

Yes.

### What is the expected behaviour?

I would _like_ the ability to easily point to a custom `store.url`. 

### What was observed?

Your `aws.custom.endpoint` is not platform agnostic. An endpoint of http://custom-host:9000 (eg. MinIO S3 store) will fail because you take the `connect.s3.kcql: INSERT INTO bucket:path` and you overwrite the URL to http://bucket.custom-host:9000, which does not exist. Not all S3-like integrations follow the bucket.DNS host pattern.

### What is your connector properties configuration (my-connector.properties)?

```YAML
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  name: minio-sink
  namespace: kafka
  labels:
    # The strimzi.io/cluster label identifies the KafkaConnect instance
    # in which to create this connector. That KafkaConnect instance
    # must have the strimzi.io/use-connector-resources annotation
    # set to true.
    strimzi.io/cluster: kafka-connect-cluster
spec:
  class: io.lenses.streamreactor.connect.aws.s3.sink.S3SinkConnector
  config:
    tasks.max: 1
    topics: test-topic
    aws.vhost.bucket: false
    aws.custom.endpoint: http://custom-host:9000/
    connect.s3.kcql: INSERT INTO bucket:bucket SELECT * FROM test-topic STOREAS `Json` WITH_FLUSH_COUNT = 1
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    key.converter.schemas.enable: false
    schemas.enable: false
````

### Context

I really expect the custom endpoint to be honored entirely _or_ you should just create a secondary `store.url` configuration which allows me to point _directly_ to the endpoint. I would also like a `bucket.name` configuration instead of pulling the bucket name dynamically from the `kcql` field. I feel like I'm missing something, but I've had to hack my way through these configurations just to make my connection
